# -*- coding: utf-8 -*-
"""process_utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hpTwxqvWXr_7Xycl-rNXFpa7emtaomM
"""

def merge_words(df):
  pattern1 = '|'.join(['Side effects', 'Side effect', 'Side-effects', 'Side-effect'])
  pattern2= '|'.join(['New strain', 'New strains', 'new strain', 'new strains'])
  df=df.str.replace(pattern1,'SideEffects',case = False)
  df=df.str.replace(pattern2,'NewStrains',case = False)
  df=df.str.replace('Availability','available',case = False)
  df=df.str.replace('affecting','affect',case = False)

  df = df.str.replace("[^A-Za-z ]", " ")
  df = df.dropna()
  return df

def merge_stop():
  from nltk.corpus import stopwords
  stop = set(stopwords.words('english'))
  stop=stop.union(set(['covid','virus','vaccine','Vaccine','Vaccines','vaccination','also','getting','even','get', 'think','vaccines','taking','yes']))

  return stop

def extract_topics(topic_list,l):
  topic=[]
  for i in range(l):
    t=topic_list[i]
    topic.append(t[0])

  return topic

